import React, { useEffect, useRef } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';

// import {
// } from '../../components';
import { RootState } from '../../store';
import {
  usePlayer,
  PlayerStatus,
  useAppSelector,
  useAppDispatch
} from '../../hooks';
// import {
// } from './components';
import {
  State,
  initial
} from './slice';

import styles from './index.module.scss';

const Main: NextPage = () => {
  const inputSongRef = useRef(null);
  const audioRef = useRef(null);

  const {
    playerUrl,
    playerStatus,
    playerProgress,
    playerUpdateUrl,
    playerPlay,
    playerPause,
    playerUpdateTime
  } = usePlayer(audioRef);

  console.log(playerUrl,
    playerStatus,
    playerProgress
  );

  const dispatch = useAppDispatch();
  const selectState = (state: RootState): State => {
    return {
      loading : state.main.loading
    }
  };
  const state: State = useAppSelector(selectState);
  
  useEffect(() => {
    // on mount
    dispatch(initial());

    return () => {
    }
  }, [])

  const onSelectSongButtonClick = () => {
    if (inputSongRef && inputSongRef.current) {
      inputSongRef.current.click();
    }
  };

  const onSelectSongChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      playerUpdateUrl(URL.createObjectURL(e.target.files[0]));
    }
  };

  const onPlayButtonClick = () => {
    if (audioRef.current) {
      if (playerStatus === PlayerStatus.STOP) {
        playerPlay();
      } else if (playerStatus === PlayerStatus.PLAY) {
        playerPause();
      } else if (playerStatus === PlayerStatus.PAUSE) {
        playerPlay();
      }
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Main</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <div
          className={styles.selectSongButton}
          onClick={onSelectSongButtonClick}
        >
          <input type="file" ref={inputSongRef} onChange={onSelectSongChange} />
          Select Song
        </div>

        <div className={styles.cover}>
          <div className={styles.coverImage}>
            <img src="" alt="" />
          </div>
          <div className={styles.artist}>artist</div>
          <div className={styles.name}>name</div>
        </div>

        <div className={styles.slider}>
          <input type="range" min="1" max="100" value="50" />
        </div>

        <div className={styles.buttonsContainer}>
          <audio ref={audioRef}>
            <source src={playerUrl} />
          </audio>

          <div
            className={styles.playButton}
            onClick={onPlayButtonClick}
          >
            {playerStatus === PlayerStatus.PLAY ?
              <i className="material-icons">pause</i>
              :
              <i className="material-icons">play_arrow</i>
            }
          </div>
        </div>
      </div>
    </div>
  );
}

export default Main;
